//
// Generated file, do not edit! Created by nedtool 5.6 from Backoff.msg.
//

#ifndef __INET_BACKOFF_M_H
#define __INET_BACKOFF_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class backoff;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/geometry/Geometry_m.h" // import inet.common.geometry.Geometry


namespace inet {

/**
 * Class generated from <tt>Backoff.msg:24</tt> by nedtool.
 * <pre>
 * class backoff extends TagBase
 * {
 *     simtime_t backoffTime;
 *     simtime_t initialBackoffTime;
 * }
 * </pre>
 */
class backoff : public ::inet::TagBase
{
  protected:
    omnetpp::simtime_t backoffTime = SIMTIME_ZERO;
    omnetpp::simtime_t initialBackoffTime = SIMTIME_ZERO;

  private:
    void copy(const backoff& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const backoff&);

  public:
    backoff();
    backoff(const backoff& other);
    virtual ~backoff();
    backoff& operator=(const backoff& other);
    virtual backoff *dup() const override {return new backoff(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual omnetpp::simtime_t getBackoffTime() const;
    virtual void setBackoffTime(omnetpp::simtime_t backoffTime);
    virtual omnetpp::simtime_t getInitialBackoffTime() const;
    virtual void setInitialBackoffTime(omnetpp::simtime_t initialBackoffTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const backoff& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, backoff& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_BACKOFF_M_H

